### ISSUE TITLE
module works with SSHD but not sudo

### ISSUE THREAD

**Issue by anthonysomerset** [jeroennijhof/pam_tacplus#12]
we just recently updated to centos 7 and the previous module we had built based on the Sourceforge version stopped working

we managed to compile this version correctly and tweak our tacacs pam.d file to allow SSH logins however sudo is no longer working with following errors (private info modified)

    sudo: pam_authenticate: Insufficient credentials to access authentication data

secure/messages log files have the following:

    ==> /var/log/messages <==
    Jul 11 11:14:00 ant-test PAM-tacplus[3463]: (pam_tacplus) converse returned 7
    Jul 11 11:14:00 ant-test PAM-tacplus[3463]: that is: Authentication failure
    Jul 11 11:14:00 ant-test PAM-tacplus[3463]: unable to obtain password
    
    ==> /var/log/secure <==
    Jul 11 11:14:00 ant-test sudo[3463]: pam_unix(sudo-i:auth): conversation failed
    Jul 11 11:14:00 ant-test sudo[3463]: pam_unix(sudo-i:auth): auth could not identify password for [username]
    Jul 11 11:14:00 ant-test sudo: asomerset : pam_authenticate: Insufficient credentials to access authentication data ; TTY=pts/1 ; PWD=/home/username ; USER=root ; COMMAND=/bin/bash

my tacacs-auth file presently looks like this:

    #%PAM-1.0
    auth            required      /lib64/security/pam_env.so
    auth       [success=done authinfo_unavail=ignore default=bad]     /usr/local/lib/security/pam_tacplus.so debug server=SERVER secret=testingtesting
    auth        include        system-auth
    account    [success=done auth_err=ignore default=bad] /usr/local/lib/security/pam_tacplus.so debug server=SERVER secret=testingtesting service=shell protocol=ssh
    account     include        system-auth
    password   required /lib64/security/pam_cracklib.so
    password   required     pam_deny.so
    session    [success=done session_err=ignore default=bad] /usr/local/lib/security/pam_tacplus.so debug server=SERVER secret=testingtesting service=shell protocol=ssh
    session     include        system-auth

any thoughts?

**Comment by muthuraman82** [comment]
I think I am also facing the same issue. Could you please give an example of how the changes should look like?
