### ISSUE TITLE
pam_tacplus-1.3.9 - install issues

### ISSUE THREAD

**Issue by gripper99** [jeroennijhof/pam_tacplus#33]
Hi

Platform - pam_tacplus.1.3.9 - redhat 6.4 - VM

I can't seem to get a version of "configure" into the installation media.
I've tried autoreconf -i
running the auto.sh 
Nothing seems to work

Can you kindly let me know where I'm going wrong?

Martin
HP Erskine - UK

**Comment by jeroennijhof** [comment]
Could you post your terminal logging from "autoreconf -i" ?
It should generate the configure file.

**Comment by gripper99** [comment]
Jeroen

Below

Many thanks for your prompt response. Most appreciated

Martin



root@pamtest pam_tacplus-1.3.9]# /usr/local/bin/autoreconf -i
[root@pamtest pam_tacplus-1.3.9]# echo $?
0
[root@pamtest pam_tacplus-1.3.9]#

Martin Bebbington
HPES Network Management Solutions
Location: Erskine Ferry Road, Bishopton, PA7 5PP
Cell: +44 7752 167274
Email:
Mbebbington@hp.com<mailto:Mbebbington@hp.com> (Unclassified email)
Martin.bebbington@ukps.ssn.hp.com<mailto:Martin.bebbington@ukps.ssn.hp.com> (Classified)

**Comment by jeroennijhof** [comment]
Could you list the files which are created by autoreconf? Just a ls -la output..

**Comment by gripper99** [comment]
Jeroen

Here lies the issue – nothing is being created.
I’m not sure what attributes the “missing configure” would have, but couldn’t you just email me a copy?

Our platform
VM Redhat 6.4 santiago
Version of pam_tacplus-1.3.9

Hope this meets with your OK and again thanks for your prompt attention

Martin



Martin Bebbington
HPES Network Management Solutions
Location: Erskine Ferry Road, Bishopton, PA7 5PP
Cell: +44 7752 167274
Email:
Mbebbington@hp.com<mailto:Mbebbington@hp.com> (Unclassified email)
Martin.bebbington@ukps.ssn.hp.com<mailto:Martin.bebbington@ukps.ssn.hp.com> (Classified)

**Comment by jeroennijhof** [comment]
Well before I send you a copy of configure I really like to understand what's going wrong, I think it has to do with your version of autotools.

Could you please run the command "autoreconf -iv" and post the output?
You should have a working aclocal, automake, autoheader, autoconf and libtoolize to have autoreconf doing its job correctly.

**Comment by gripper99** [comment]
Jerone

Your list

aclocal

missing



automake

yum install automake

version 1.11.1-4.e16.noarch already installed

autoheader /autoconf

Autoconf Version 2.13



libtoolize

missing






[root@pamtest pam_tacplus-1.3.9]# autoreconf -iv
Usage: autoreconf [-f] [-h] [--help] [-m dir] [--macrodir=dir]
       [-l dir] [--localdir=dir] [--force] [--verbose] [--version]
       [--cygnus] [--foreign] [--gnits] [--gnu] [-i] [--include-deps]
[root@pamtest pam_tacplus-1.3.9]# autoreconf --version
Autoconf version 2.13


Do you want me to try and install – somehow – alocal & libtoolize

Again – many thanks for your prompt response

Martin


Martin Bebbington
HPES Network Management Solutions
Location: Erskine Ferry Road, Bishopton, PA7 5PP
Cell: +44 7752 167274
Email:
Mbebbington@hp.com<mailto:Mbebbington@hp.com> (Unclassified email)
Martin.bebbington@ukps.ssn.hp.com<mailto:Martin.bebbington@ukps.ssn.hp.com> (Classified)

**Comment by jeroennijhof** [comment]
Yes you really need aclocal and libtoolize so please install them. And I see your autoreconf version differ so you should run "autoreconf --verbose -i".

**Comment by gripper99** [comment]
Jeroen

Slightly miss leading information in my last:

This the status:


aclocal

OK

1.11.1

automake

yum install automake

version 1.11.1-4.e16.noarch already installed

autoheader /autoconf

Autoconf Version 2.13



libtoolize

OK

couldn't get a version but yum whatprovides gives libtool 2.2.6-15.5


Autoreconf –verbose –I returns nothing


Thanks again..


Martin Bebbington
HPES Network Management Solutions
Location: Erskine Ferry Road, Bishopton, PA7 5PP
Cell: +44 7752 167274
Email:
Mbebbington@hp.com<mailto:Mbebbington@hp.com> (Unclassified email)
Martin.bebbington@ukps.ssn.hp.com<mailto:Martin.bebbington@ukps.ssn.hp.com> (Classified)

**Comment by jeroennijhof** [comment]
Ok please run the following commands which actually should be done by autoreconf:
- aclocal
- autoconf
- automake --add-missing

**Comment by gripper99** [comment]
Jeroen

We have a bank holiday this weekend so will be finishing soon, so will google this error code.
If I don’t hear from before close, “fijn weekend” – lived in Noordwijk-an-zee for two years … very nice..

Thanks again

Martin

·         aclocal

warning: macro `AM_PROG_LIBTOOL` not found in library



·         /usr/bin/autoconf

Possibly underfined macro ÀM_PROG_LIBTOOL`



·         automake --add-missing

Usage: autoconf [-h] [--help] [-m dir] [--macrodir=dir]

       [-l dir] [--localdir=dir] [--version] [template-file]

Martin Bebbington
HPES Network Management Solutions
Location: Erskine Ferry Road, Bishopton, PA7 5PP
Cell: +44 7752 167274
Email:
Mbebbington@hp.com<mailto:Mbebbington@hp.com> (Unclassified email)
Martin.bebbington@ukps.ssn.hp.com<mailto:Martin.bebbington@ukps.ssn.hp.com> (Classified)

**Comment by jeroennijhof** [comment]
Well you could try to run libtoolize first but this has really todo with your version of automake you should try to update it to a newer version but first try:
- libtoolize
- aclocal
- autoheader
- autoconf
- automake

**Comment by gripper99** [comment]
What options for automake Jeroen?

Doesn’t like the –add-missing

Martin Bebbington
HPES Network Management Solutions
Location: Erskine Ferry Road, Bishopton, PA7 5PP
Cell: +44 7752 167274
Email:
Mbebbington@hp.com<mailto:Mbebbington@hp.com> (Unclassified email)
Martin.bebbington@ukps.ssn.hp.com<mailto:Martin.bebbington@ukps.ssn.hp.com> (Classified)

**Comment by jeroennijhof** [comment]
No options just run automake without any option.
