### ISSUE TITLE
configure fails for Redhat 6.4 and Redhat 6.6

### ISSUE THREAD

**Issue by GeorgeOikonomou** [jeroennijhof/pam_tacplus#34]
Hello,

I have issues with RHEL 6.4 and RHEL 6.6:

./configure: line 12103: syntax error near unexpected token AX_CHECK_COMPILE_FLAG' ./configure: line 12103:AX_CHECK_COMPILE_FLAG("-fstack-protector-all", AX_APPEND_FLAG(["-fstack-protector-all"],[CFLAGS]), )'

The configure script fails.

I believe it is related with issue: https://github.com/jeroennijhof/pam_tacplus/issues/22

Thanks,
George

**Comment by kravietz** [comment]
This is a problem with older autoconf/automake that miss the AX_ checks - you might just comment out these checks from the configure.am file.

**Comment by GeorgeOikonomou** [comment]
Thank you, it worked for RHEL 6.6.

**Comment by davidbornog** [comment]
Hi kravietz,

there is no AX_ checks command in configure.am and if I delete AX_check in configure file, the command will write back automatically when I run make; or makefile; command 
really need ur help

**Comment by pprindeville** [comment]
Okay, dumb question... what happens if you run `autoreconf -f -i` before configure?

**Comment by davidbornog** [comment]
Big thanks, it works now (CentOS 6.8)
