### ISSUE TITLE
Invalid packet header and length test 

### ISSUE THREAD

**Issue by daveholland59** [jeroennijhof/pam_tacplus#48]
The following test is invalid. 
```
if (len_from_header > packet_read) {
        TACSYSLOG((LOG_ERR,
            "%s: length declared in the packet %d does not match actual packet size %d",
            __FUNCTION__,
            len_from_header, packet_read))
        re->status = LIBTAC_STATUS_PROTOCOL_ERR;
        free(tb);
        return re->status;
      }
```   
packet_read contains length of header only. len_from_header contains length of packet body only. The two things are incomparable.
This code fragment occurs in three different files; authen_r.c, author_r.c, acct_r.c.
The remedy is to remove the test.

**Comment by kravietz** [comment]
Correct. I have just replaced this with a hard-coded maximum packet length currently set at 128 KB. It just didn't feel good with allocating memory of arbitrary size passed from the network.
