### ISSUE TITLE
Undefined symbol 'magic' in pam_tacplus.so

### ISSUE THREAD

**Issue by shankarunni** [jeroennijhof/pam_tacplus#54]
Looks like when the calls to magic() were being replaced by equivalent openssl RAND_pseudo_bytes() calls, one spot was missed: in the top-level pam_tacplus.c itself (in pam_sm_open_session()).

Patch : https://gist.github.com/shankarunni/57f3467931bbf97d90000c0f7df78764

**Comment by kravietz** [comment]
Thank you, fixed!
