### ISSUE TITLE
Incorrect clearing of areply struct

### ISSUE THREAD

**Issue by SophiasDad** [jeroennijhof/pam_tacplus#56]
There are two blocks of code with this sort of structure in pam_tacplus.c

        while (communicating) {
            struct areply re = { .attr = NULL, .msg = NULL, status = 0, flags = 0 };

The problem is that there's a missing . before status and flags.  At least with my compiler, and I suspect all compilers, this does not clear re.status, but rather the enclosing local variable status(and presumably flags, but I'm not interested in that one).  

The unfortunate consequence of the above is that the status field had been set to something 'bad' intentionally in the outer context.  For instance, PAM_AUTHINFO_UNAVAIL.  This would normally mean that if all servers couldn't be contacted or had other problems(like bad shared secret), the return would be some form of failure.  

With this bug in place, that status becomes PAM_SUCCESS immediately upon entry of the while loop, and if no servers can be contacted(or even the first server can't be contacted), the return from this function is PAM_SUCCESS, and users are mistakenly authenticated.

**Comment by kravietz** [comment]
Thank you, good find!
