### ISSUE TITLE
License of libtac

### ISSUE THREAD

**Issue by aniruddha-a** [jeroennijhof/pam_tacplus#57]
Hello,

If I want to use only the `libtac` part (the library alone) from this project, will
it be under GPL, or LGPL?

Thanks.

**Comment by kravietz** [comment]
As of now the whole package is licensed under GPL but I can create a separet LGPL license for the library component.

**Comment by aniruddha-a** [comment]
Thank you. That'll help. Will it be part of this repo or separate?
