### ISSUE TITLE
clang (Apple llvm-gcc)

### ISSUE THREAD

**Issue by vollkommenheit** [jeroennijhof/pam_tacplus#74]
I get:

```
./auto.sh
./configure
make
...
support.c:115:11: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
    flags = flags;                              /* unused */
    ~~~~~ ^ ~~~~~
1 error generated.
make[1]: *** [pam_tacplus_la-support.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
pam_tacplus.c:512:7: error: explicitly assigning value of variable of type 'pam_handle_t _' (aka 'struct pam_handle *') to itself [-Werror,-Wself-assign]
        pamh = pamh;
        ~~~~ ^ ~~~~
pam_tacplus.c:513:8: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
        flags = flags;                          /* unused */
        ~~~~~ ^ ~~~~~
pam_tacplus.c:538:8: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
        flags = flags;                          /* unused */
        ~~~~~ ^ ~~~~~
pam_tacplus.c:707:8: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
        flags = flags;                          /* unused */
        ~~~~~ ^ ~~~~~
pam_tacplus.c:720:8: error: explicitly assigning value of variable of type 'int' to itself [-Werror,-Wself-assign]
        flags = flags;                          /* unused */
        ~~~~~ ^ ~~~~~
5 errors generated.
make[1]: *** [pam_tacplus_la-pam_tacplus.lo] Error 1
make: *** [all] Error 2
```

```
gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

```
llvm-gcc --version
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I've tried the following, to no avail:
```
export CCACHE_CPP2=yes
export run_second_cpp=true
```

**Comment by daveolson53** [comment]
vollkommenheit <notifications@github.com> wrote:

> I get:
> 
> ./auto.sh
> ./configure
> make
> ...
> support.c:115:11: error: explicitly assigning value of variable of type 'int'
> to itself [-Werror,-Wself-assign]
> flags = flags; /* unused /

Looks like this comes from Phillip Prindeville's commit
91b8449a4085071318b353c987b4ac500c7b3803

It was deliberate, but...

Since both gcc and clang support
  __attribute__((unused))
that would probably be a better method to flag the unused variables
that the API requires.

> ~~~~~ ^ ~~~~~
> 1 error generated.
> make[1]: ** [pam_tacplus_la-support.lo] Error 1
> make[1]: *** Waiting for unfinished jobs....
> pam_tacplus.c:512:7: error: explicitly assigning value of variable of type
> 'pam_handle_t ' (aka 'struct pam_handle *') to itself [-Werror,-Wself-assign]
> pamh = pamh;
> ~~~~ ^ ~~~~
> pam_tacplus.c:513:8: error: explicitly assigning value of variable of type
> 'int' to itself [-Werror,-Wself-assign]
> flags = flags; / unused /
> ~~~~~ ^ ~~~~~
> pam_tacplus.c:538:8: error: explicitly assigning value of variable of type
> 'int' to itself [-Werror,-Wself-assign]
> flags = flags; / unused /
> ~~~~~ ^ ~~~~~
> pam_tacplus.c:707:8: error: explicitly assigning value of variable of type
> 'int' to itself [-Werror,-Wself-assign]
> flags = flags; / unused /
> ~~~~~ ^ ~~~~~
> pam_tacplus.c:720:8: error: explicitly assigning value of variable of type
> 'int' to itself [-Werror,-Wself-assign]
> flags = flags; / unused /
> ~~~~~ ^ ~~~~~
> 5 errors generated.
> make[1]: ** [pam_tacplus_la-pam_tacplus.lo] Error 1
> make: *** [all] Error 2
> 
> gcc --version
> Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr
> --with-gxx-include-dir=/usr/include/c++/4.2.1
> Apple LLVM version 8.0.0 (clang-800.0.38)
> Target: x86_64-apple-darwin15.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/
> XcodeDefault.xctoolchain/usr/bin
> 
> llvm-gcc --version
> Apple LLVM version 8.0.0 (clang-800.0.38)
> Target: x86_64-apple-darwin15.6.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/
> XcodeDefault.xctoolchain/usr/bin
> 
> I've tried the following, to no avail:
> export CCACHE_CPP2=yes
> export run_second_cpp=true
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

Dave Olson
olson@cumulusnetworks.com

**Comment by pprindeville** [comment]
> Since both gcc and clang support
> `attribute((unused))`
> that would probably be a better method to flag the unused variables that the API requires.

Are there any environments (like Solaris or Greenhills cc) that we use where that attribute isn't supported?

**Comment by pprindeville** [comment]
@vollkommenheit Please test the fix in PR #106 and report back.

**Comment by vollkommenheit** [comment]
Now getting the following during make, not sure if it's a new issue or related to the existing one:

libtool: link: gcc -Wl,-undefined -Wl,dynamic_lookup -o .libs/pam_tacplus.so -bundle  .libs/pam_tacplus_la-pam_tacplus.o .libs/pam_tacplus_la-support.o   ./.libs/libtac.dylib -L/usr/local/lib /Users/schlachtschiff/src/pam_tacplus/.libs/libtac.dylib -lutil -lcrypto /usr/local/lib/libtac.dylib -lpam  -g -O2 -O3 -march=native -flto
libtool: link: ( cd ".libs" && rm -f "pam_tacplus.la" && ln -s "../pam_tacplus.la" "pam_tacplus.la" )
gcc -DHAVE_CONFIG_H -I.    -Wall -Wextra -Werror -I ./libtac/include  -g -O2 -MT tacc-tacc.o -MD -MP -MF .deps/tacc-tacc.Tpo -c -o tacc-tacc.o `test -f 'tacc.c' || echo './'`tacc.c
tacc.c: In function 'main':
tacc.c:359:3: error: implicit declaration of function 'logwtmp' [-Werror=implicit-function-declaration]
   logwtmp(tty, user, "dialup");
   ^
cc1: all warnings being treated as errors
make[1]: *** [tacc-tacc.o] Error 1
make: *** [all] Error 2

**Comment by pprindeville** [comment]
This is a new and unrelated issue.  Please open a new issue.  Also include if your system have a `logwtmp()` function, what header it's declared in, and what library provides it.

**Comment by pprindeville** [comment]
See PR #107 also.
