### ISSUE TITLE
Unable to build deb package.

### ISSUE THREAD

**Issue by suviswan** [jeroennijhof/pam_tacplus#92]
I am trying to build the debian package from the source code using dpkg-buildpackage -B command and getting the below error.

```
cp: cannot stat 'debian/tmp/usr/sbin': No such file or directory
dh_install: cp -a debian/tmp/usr/sbin debian/libtac2-bin//usr/ returned exit code 1
make[1]: *** [override_dh_install] Error 2
make[1]: Leaving directory `/root/pam_source/pam_tacplus-master'
make: *** [binary] Error 2
dpkg-buildpackage: error: debian/rules binary gave error exit status 2
```

On analysis the tacc file is installed into debian/tmp/usr/bin/tacc, but "debian/libtac2-bin.install" looks the files in usr/sbin.  Changing this to usr/bin fixes the issue. Can you update the source code or let me how to handle it ?

**Comment by pprindeville** [comment]
Can you please post all your steps and I'll try to reproduce it.

**Comment by pprindeville** [comment]
Closed for lack of actionable response.
